"""ingredient, recette, relation

Revision ID: 114ffcc41690
Revises: 
Create Date: 2021-11-15 16:22:20.379833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114ffcc41690'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('unite', sa.String(length=64), nullable=True),
    sa.Column('qte', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_cost'), 'ingredient', ['cost'], unique=False)
    op.create_index(op.f('ix_ingredient_name'), 'ingredient', ['name'], unique=True)
    op.create_index(op.f('ix_ingredient_unite'), 'ingredient', ['unite'], unique=False)
    op.create_table('recette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recette_cost'), 'recette', ['cost'], unique=False)
    op.create_index(op.f('ix_recette_name'), 'recette', ['name'], unique=True)
    op.create_table('relation',
    sa.Column('recette_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('qte_necessaire', sa.Integer(), nullable=True),
    sa.Column('qte_achat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recette_id'], ['recette.id'], ),
    sa.PrimaryKeyConstraint('recette_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation')
    op.drop_index(op.f('ix_recette_name'), table_name='recette')
    op.drop_index(op.f('ix_recette_cost'), table_name='recette')
    op.drop_table('recette')
    op.drop_index(op.f('ix_ingredient_unite'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_name'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_cost'), table_name='ingredient')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
